apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-app-cronjob
spec:
  schedule: "0 0 * * *"  # every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-app
            image: denvash/go-demo-app:1.0
          restartPolicy: OnFailure
