apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-secret-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: denvash/go-demo-app:1.0
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret-key
