apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-multicontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: main
        image: denvash/go-demo-app:1.0
        ports:
        - containerPort: 8080
      - name: sidecar
        image: denvash/sidecar:1.0
